### ISSUE TITLE
Consider using TypeScript?

### ISSUE THREAD

**Issue by jcbhmr** [skdhg/node-navigator#1]
I think transitioning to TypeScript could be beneficial. For instance, getting all the spec-compliant(ish) stuff typed right _in the same file as you implement it_ is a good idea in my opinion. This would give in-file autocomplete without needing to keep a `typings/*` .d.ts file in sync. 😊

This would also help with implementing interfaces with `class A implements B, C {}` and such with _native syntax_ instead of going through a JSDoc layer.

I am willing and want to open a PR to make this happen  ❤️

**Comment by jcbhmr** [comment]
@skdhg friendly ping 💌 I notice you aren't "watching" this repo 😅 #2 #3 #4 

https://github.com/skdhg/node-navigator/watchers
![image](https://github.com/skdhg/node-navigator/assets/61068799/0155beec-3447-4c87-9168-8a69ba23bc3c)

**Comment by twlite** [comment]
> @skdhg friendly ping 💌 I notice you aren't "watching" this repo 😅 #2 #3 #4
> 
> https://github.com/skdhg/node-navigator/watchers ![image](https://user-images.githubusercontent.com/61068799/241015487-0155beec-3447-4c87-9168-8a69ba23bc3c.png)

😅 it's been a really long time since i did anything here
