### ISSUE TITLE
Add automation!

### ISSUE THREAD

**Issue by jcbhmr** [skdhg/node-navigator#3]
GitHub Actions can do a lot of magic stuff for you without much work! Here's some things that a lot of npm packages have that I'd like to add to this project:

1. [x] A test workflow that runs `npm test` on each Node LTS version
2. [x] A publish workflow to auto run `npm publish` with an npm token on each release

**Comment by twlite** [comment]
@jcbhmr I may not be able to review everything here so I've added you as a collaborator, feel free to make any changes 😄

You can contact me on discord if needed https://discord.com/users/916316955772862475

**Comment by jcbhmr** [comment]
Sounds good! ❤️ Thanks for trusting me with Collaborator privileges! 😊

I'll try to:
1. Not make any breaking changes without communication and stuff (approval, discussion, etc)
2. Keep scope _restrained_ to implementing the HTML Navigator interface, not _every_ Navigator interface
3. Make improvements to tooling so that, hopefully, you don't need to do much manual work (GH Actions are awesome) 😎
4. Improve the documentation surrounding this project
